### ISSUE TITLE
npm run task remap-istanbul-html broken

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/punchcardjs#45]
in 24cc691629b939d5a2b370b112db46d4951516c0. something's not right with the source maps. check content of source maps here https://www.base64decode.org/

**Comment by jspaaks** [comment]
Here's some output

```
> remap-istanbul --input sites/coverage/coverage-remapped.json --output sites/coverage/remapped --type html --exclude node_modules

Excluding: "node_modules/browserify/node_modules/browser-pack/_prelude.js"
[Error: Could not find source map for: "build/src/base.ts"]
[Error: Could not find source map for: "src/colormap.ts"]
[Error: Could not find source map for: "build/src/date-circle.ts"]
[Error: Could not find source map for: "build/src/date-rect.ts"]
[Error: Could not find source map for: "build/src/legend.ts"]
[Error: Could not find source map for: "src/punchcards.ts"]
[Error: Could not find source map for: "build/src/weekday-circle.ts"]
[Error: Could not find source map for: "build/src/weekday-rect.ts"]
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'build/src/base.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at LookupStore.Store.mix.get (/home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/store/fslookup.js:40:19)
    at HtmlReport.Report.mix.writeDetailPage (/home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:411:67)
    at /home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /home/daisycutter/github/nlesc-sherlock/punchcardjs/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "remap-istanbul-html"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! punchcards@1.0.0 remap-istanbul-html: `remap-istanbul --input sites/coverage/coverage-remapped.json --output sites/coverage/remapped --type html --exclude node_modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the punchcards@1.0.0 remap-istanbul-html script 'remap-istanbul --input sites/coverage/coverage-remapped.json --output sites/coverage/remapped --type html --exclude node_modules'.
npm ERR! This is most likely a problem with the punchcards package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     remap-istanbul --input sites/coverage/coverage-remapped.json --output sites/coverage/remapped --type html --exclude node_modules
npm ERR! You can get their info via:
npm ERR!     npm owner ls punchcards
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daisycutter/github/nlesc-sherlock/punchcardjs/npm-debug.log

```

**Comment by jspaaks** [comment]
In `tsconfig`, I have 

```
{
    "compilerOptions": {
        "outDir": "build",
        "inlineSourceMap": true,
        "inlineSources": true
    },
    ...
}
```

If I do

``` bash
npm run clean
npm run tsc
```

and then

```
ls -1 build/
```

I get

```
base.js
colormap.js
date-circle.js
date-rect.js
idatarow.js
legend.js
punchcards.js
weekday-circle.js
weekday-rect.js
```

feeding the source maps from those files to https://www.base64decode.org/
- base.js `"sources":["../src/base.ts"]`
- colormap.js `"sources":["../src/colormap.ts"]`
- date-circle.js `"sources":["../src/date-circle.ts"]`
- date-rect.js `"sources":["../src/date-rect.ts"]`
- idatarow.js `["../src/idatarow.ts"]`
- legend.js `["../src/legend.ts"]`
- punchcards.js `"sources":["../src/punchcards.ts"]`
- weekday-circle.js `"sources":["../src/weekday-circle.ts"]`
- weekday-rect.js `"sources":["../src/weekday-rect.ts"]`

property `sourceRoot` is emtpy for all js files in `build/`

So all looks good at this point. 

If I then do 

```
npm run dist
```

, the sourcemap in `dist/punchcards.js` contains the following snippet:

```
"sources":[
   "node_modules/browserify/node_modules/browser-pack/_prelude.js",
   "build/src/base.ts",
   "src/colormap.ts",
   "build/src/date-circle.ts",
   "build/src/date-rect.ts",
   "build/src/legend.ts",
   "src/punchcards.ts",
   "build/src/weekday-circle.ts",
   "build/src/weekday-rect.ts"
]
```

With this setup I can see the ts code in the browser/debugging in the browser works, even if the browser thinks some of the code is located in 'build' and some of it in 'build/src'. Code coverage generation though is broken.

So this is where it goes wrong.

**Comment by jspaaks** [comment]
Investigated some tools that can follow multiple levels of source maps
- [UglifyJS](https://github.com/mishoo/UglifyJS2)
- [sorcery](https://github.com/rich-harris/sorcery)
- [minifyify](https://www.npmjs.com/package/minifyify)

no luck so far

[finally](https://github.com/nlesc-sherlock/punchcardjs/tree/af000ee35a8abe8c346b73d0430dd155e13eaba3) some progress with [tsify](https://www.npmjs.com/package/tsify) plugin for browserify
